export const taskSuggestions = [
  "finish homework",
  "review class notes",
  "study for math test",
  "complete group project",
  "read assigned chapters",
  "write essay draft",
  "revise for upcoming quiz",
  "submit assignment before deadline",
  "organize study materials",
  "practice coding exercises",
  "watch lecture recordings",
  "attend study group",
  "check email for class updates",
  "buy groceries",
  "do laundry",
  "walk the dog",
  "call mom",
  "clean the house",
  "pay bills",
  "read a book",
  "exercise for 30 minutes",
  "meal prep for the week",
  "respond to messages",
  "plan weekend activities",
  "set up reminders for tasks",
  "schedule a break from studying",
  "watch a movie",
  "listen to a podcast",
  "organize desk space",
  "take out the trash",
  "prepare for class discussion",
  "proofread essay before submission",
  "backup important files",
  "download required textbooks",
  "practice speaking for oral exam",
  "apply for internships",
  "recharge laptop before class",
  "write daily reflection journal",
  "plan project timeline",
  "send follow-up email to professor",
  "clean up phone storage",
  "catch up on sleep",
  "try a new recipe",
  "write in a journal",
  "meditate for 10 minutes"
];



export const todoQuotes = [
  "Small steps every day lead to big changes. Keep going!",
  "Your future is created by what you do today, not tomorrow.",
  "Don’t let perfectionism stop you from making progress.",
  "Success is the sum of small efforts repeated daily.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Dream big, start small, but most of all, start!",
  "The secret of getting ahead is getting started.",
  "A goal without a plan is just a wish.",
  "Make today so awesome that yesterday gets jealous.",
  "It always seems impossible until it’s done.",
  "Do something today that your future self will thank you for.",
  "Start where you are. Use what you have. Do what you can.",
  "Discipline is the bridge between goals and accomplishment.",
  "Productivity isn’t about doing more, it’s about doing what matters.",
  "Make progress, not excuses."
];
